package com.novacasino.infrastructure.rng;

import com.novacasino.domain.rng.RngEngine;
import com.novacasino.domain.rng.RngFactory;
import org.springframework.stereotype.Component;

import java.util.Random;

/**
 * {@link RngFactory} adapter backed by {@link java.util.Random}. Its linear-congruential algorithm is
 * specified by the JDK and therefore produces the <strong>same sequence for a given seed on any
 * machine</strong>, which is exactly what replay and golden-master recomputation need (readme §2.1.7).
 *
 * <p>The per-round seed itself is generated by the spin use case from a {@code SecureRandom}; this
 * factory only turns a known seed into a reproducible engine.
 */
@Component
public class JavaRandomRngFactory implements RngFactory {

    @Override
    public RngEngine create(final long seed) {
        final Random random = new Random(seed);
        return random::nextInt;
    }
}
