-- =============================================================================
-- V14__finetune_seed_rtp.sql — HU-31 (ajuste fino): los 3 juegos centrados en su RTP objetivo
-- (egyptian 95%, fruits 92%, space 96.5%). game_configs es append-only: se inserta la siguiente
-- versión calibrada por juego y se activa. Sólo actúa sobre BBDD ya sembradas (existe la versión
-- activa previa); no-op en instalaciones nuevas (SeedDataLoader inserta la v1 ya calibrada).
-- =============================================================================

-- Egyptian (target 0.95): v3 -> v4
INSERT INTO game_configs (game_id, version, config, rtp_target, volatility_target, created_by_user_id, notes)
SELECT g.id, 4, '{"grid":{"cols":5,"rows":3},"symbols":[{"id":"WILD","kind":"WILD"},{"id":"SCATTER","kind":"SCATTER"},{"id":"ANUBIS","kind":"REGULAR"},{"id":"SCARAB","kind":"REGULAR"},{"id":"A","kind":"REGULAR"}],"reels":[["A","SCARAB","A","ANUBIS","A","SCARAB","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","A","A"],["A","SCARAB","A","ANUBIS","A","SCARAB","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","A","A"],["A","SCARAB","A","ANUBIS","A","SCARAB","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","A","A"],["A","SCARAB","A","ANUBIS","A","SCARAB","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","A","A"],["A","SCARAB","A","ANUBIS","A","SCARAB","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","A","A"]],"paylines":[[1,1,1,1,1],[0,0,0,0,0],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2]],"paytable":[{"symbol":"ANUBIS","payouts":{"3":5,"4":20,"5":90}},{"symbol":"SCARAB","payouts":{"3":2,"4":4,"5":19}},{"symbol":"A","payouts":{"4":1,"5":3}}],"scatterPays":{"SCATTER":{"3":2,"4":8,"5":40}},"bonus":{"wild":{"substitutes":["REGULAR"]},"freeSpins":{"triggerSymbol":"SCATTER","minTriggerCount":3,"award":{"3":5,"4":8,"5":12},"multiplier":2,"retrigger":false}}}'::jsonb, 0.9500, 8.50, c.created_by_user_id, 'Fine-tuned RTP to 95% (HU-31)'
FROM   games g JOIN game_configs c ON c.game_id = g.id AND c.version = 3
WHERE  g.code = 'egyptian-5x3';
UPDATE games SET active_config_id = (SELECT id FROM game_configs WHERE game_id = games.id AND version = 4)
WHERE  code = 'egyptian-5x3' AND EXISTS (SELECT 1 FROM game_configs WHERE game_id = games.id AND version = 4);

-- Fruits (target 0.92): v2 -> v3
INSERT INTO game_configs (game_id, version, config, rtp_target, volatility_target, created_by_user_id, notes)
SELECT g.id, 3, '{"grid":{"cols":3,"rows":3},"symbols":[{"id":"SEVEN","kind":"REGULAR"},{"id":"BAR3","kind":"REGULAR"},{"id":"BAR2","kind":"REGULAR"},{"id":"BAR","kind":"REGULAR"},{"id":"CHERRY","kind":"REGULAR"},{"id":"LEMON","kind":"REGULAR"},{"id":"ORANGE","kind":"REGULAR"},{"id":"PLUM","kind":"REGULAR"}],"reels":[["SEVEN","BAR3","BAR2","CHERRY","BAR","LEMON","ORANGE","PLUM","BAR2","CHERRY","BAR","LEMON","ORANGE","PLUM","BAR2"],["CHERRY","PLUM","LEMON","ORANGE","BAR","BAR2","BAR3","SEVEN","CHERRY","PLUM","LEMON","ORANGE","BAR","BAR2","BAR3"],["LEMON","ORANGE","CHERRY","PLUM","BAR","BAR2","BAR3","SEVEN","LEMON","ORANGE","CHERRY","PLUM","BAR","BAR2","SEVEN"]],"paylines":[[1,1,1],[0,0,0],[2,2,2],[0,1,2],[2,1,0]],"paytable":[{"symbol":"SEVEN","payouts":{"3":280}},{"symbol":"BAR3","payouts":{"3":140}},{"symbol":"BAR2","payouts":{"3":70}},{"symbol":"BAR","payouts":{"2":3,"3":25}},{"symbol":"CHERRY","payouts":{"2":6,"3":13}},{"symbol":"LEMON","payouts":{"2":3,"3":8}},{"symbol":"ORANGE","payouts":{"2":3,"3":8}},{"symbol":"PLUM","payouts":{"2":3,"3":8}}],"bonus":{}}'::jsonb, 0.9200, 3.00, c.created_by_user_id, 'Fine-tuned RTP to 92% (HU-31)'
FROM   games g JOIN game_configs c ON c.game_id = g.id AND c.version = 2
WHERE  g.code = 'fruits-3x3';
UPDATE games SET active_config_id = (SELECT id FROM game_configs WHERE game_id = games.id AND version = 3)
WHERE  code = 'fruits-3x3' AND EXISTS (SELECT 1 FROM game_configs WHERE game_id = games.id AND version = 3);

-- Space (target 0.965): v2 -> v3
INSERT INTO game_configs (game_id, version, config, rtp_target, volatility_target, created_by_user_id, notes)
SELECT g.id, 3, '{"grid":{"cols":5,"rows":3},"symbols":[{"id":"WILD","kind":"WILD"},{"id":"SCATTER","kind":"SCATTER"},{"id":"PLANET","kind":"REGULAR"},{"id":"COMET","kind":"REGULAR"},{"id":"STAR","kind":"REGULAR"},{"id":"K","kind":"REGULAR"},{"id":"A","kind":"REGULAR"}],"reels":[["A","K","A","STAR","A","K","COMET","A","K","STAR","A","SCATTER","A","K","STAR","COMET","A","K","A","STAR","PLANET","A","K","STAR","A","COMET","A","K","SCATTER","WILD"],["A","K","A","STAR","A","K","COMET","A","K","STAR","A","SCATTER","A","K","STAR","COMET","A","K","A","STAR","PLANET","A","K","STAR","A","COMET","A","K","SCATTER","WILD"],["A","K","A","STAR","A","K","COMET","A","K","STAR","A","SCATTER","A","K","STAR","COMET","A","K","A","STAR","PLANET","A","K","STAR","A","COMET","A","K","SCATTER","WILD"],["A","K","A","STAR","A","K","COMET","A","K","STAR","A","SCATTER","A","K","STAR","COMET","A","K","A","STAR","PLANET","A","K","STAR","A","COMET","A","K","SCATTER","WILD"],["A","K","A","STAR","A","K","COMET","A","K","STAR","A","SCATTER","A","K","STAR","COMET","A","K","A","STAR","PLANET","A","K","STAR","A","COMET","A","K","SCATTER","WILD"]],"paylines":[[1,1,1,1,1],[0,0,0,0,0],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2],[0,0,1,2,2],[2,2,1,0,0],[1,0,0,0,1],[1,2,2,2,1],[0,1,0,1,0]],"paytable":[{"symbol":"PLANET","payouts":{"3":20,"4":62,"5":205}},{"symbol":"COMET","payouts":{"3":10,"4":31,"5":103}},{"symbol":"STAR","payouts":{"3":4,"4":13,"5":48}},{"symbol":"K","payouts":{"3":2,"4":6,"5":20}},{"symbol":"A","payouts":{"4":3,"5":4}}],"scatterPays":{"SCATTER":{"3":4,"4":16,"5":82}},"bonus":{"wild":{"substitutes":["REGULAR"]},"freeSpins":{"triggerSymbol":"SCATTER","minTriggerCount":3,"award":{"3":5,"4":8,"5":12},"multiplier":2,"retrigger":false}}}'::jsonb, 0.9650, 12.00, c.created_by_user_id, 'Fine-tuned RTP to 96.5% (HU-31)'
FROM   games g JOIN game_configs c ON c.game_id = g.id AND c.version = 2
WHERE  g.code = 'space-5x3';
UPDATE games SET active_config_id = (SELECT id FROM game_configs WHERE game_id = games.id AND version = 3)
WHERE  code = 'space-5x3' AND EXISTS (SELECT 1 FROM game_configs WHERE game_id = games.id AND version = 3);
