-- =============================================================================
-- V15__finetune_egyptian_rtp.sql — HU-31 (ajuste fino final): "Tesoro del Nilo" queda en 95,0%
-- (medido a 10M). Baja ANUBIS (5-de-una: 90 -> 70) sobre la v4. append-only: inserta la v5 y la
-- activa. No-op en instalaciones nuevas (SeedDataLoader ya inserta la v1 calibrada).
-- =============================================================================

INSERT INTO game_configs (game_id, version, config, rtp_target, volatility_target, created_by_user_id, notes)
SELECT g.id, 5, '{"grid":{"cols":5,"rows":3},"symbols":[{"id":"WILD","kind":"WILD"},{"id":"SCATTER","kind":"SCATTER"},{"id":"ANUBIS","kind":"REGULAR"},{"id":"SCARAB","kind":"REGULAR"},{"id":"A","kind":"REGULAR"}],"reels":[["A","SCARAB","A","ANUBIS","A","SCARAB","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","A","A"],["A","SCARAB","A","ANUBIS","A","SCARAB","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","A","A"],["A","SCARAB","A","ANUBIS","A","SCARAB","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","A","A"],["A","SCARAB","A","ANUBIS","A","SCARAB","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","A","A"],["A","SCARAB","A","ANUBIS","A","SCARAB","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","WILD","A","SCARAB","A","SCATTER","A","SCARAB","ANUBIS","A","SCARAB","A","A","A"]],"paylines":[[1,1,1,1,1],[0,0,0,0,0],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2]],"paytable":[{"symbol":"ANUBIS","payouts":{"3":5,"4":20,"5":70}},{"symbol":"SCARAB","payouts":{"3":2,"4":4,"5":19}},{"symbol":"A","payouts":{"4":1,"5":3}}],"scatterPays":{"SCATTER":{"3":2,"4":8,"5":40}},"bonus":{"wild":{"substitutes":["REGULAR"]},"freeSpins":{"triggerSymbol":"SCATTER","minTriggerCount":3,"award":{"3":5,"4":8,"5":12},"multiplier":2,"retrigger":false}}}'::jsonb, 0.9500, 8.50, c.created_by_user_id, 'Fine-tuned RTP to 95% (HU-31)'
FROM   games g JOIN game_configs c ON c.game_id = g.id AND c.version = 4
WHERE  g.code = 'egyptian-5x3';
UPDATE games SET active_config_id = (SELECT id FROM game_configs WHERE game_id = games.id AND version = 5)
WHERE  code = 'egyptian-5x3' AND EXISTS (SELECT 1 FROM game_configs WHERE game_id = games.id AND version = 5);
